TPASPKT-698 Fix a pathlib bug not caught by unit tests
Integration test failed due to error in cleanup script:

    AttributeError: 'str' object has no attribute 'relative_to'